version: '3.5'
services: 
  app:
    build:
      context: .
    ports:
      - 3001:3001
    volumes:
      - ./:/app
  db:
    build: 
      context: ./postgres
    restart: always
    container_name: ruby_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./tmp/postgres:/tmp/postgres
